---
swagger: "2.0"
info:
  description: Api Documentation
  version: "1.0"
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:4200
basePath: /
tags:
- name: basic-error-controller
  description: Basic Error Controller
- name: resource-controller
  description: Resource Controller
- name: user-controller
  description: User Controller
paths:
  /api/v1/resource/auth:
    post:
      tags:
      - resource-controller
      summary: auth
      operationId: authUsingPOST
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - in: body
        name: dto
        description: dto
        required: true
        schema:
          $ref: '#/definitions/EvaSearchReqDto'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ApiResponse'
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /api/v1/resource/eva-flight-search:
    post:
      tags:
      - resource-controller
      summary: evaSearch
      operationId: evaSearchUsingPOST
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - in: body
        name: flightSearchInfo
        description: flightSearchInfo
        required: true
        schema:
          $ref: '#/definitions/FlightSearchInfo'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ApiResponse'
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /api/v1/resource/test:
    get:
      tags:
      - resource-controller
      summary: testApi
      operationId: testApiUsingGET
      produces:
      - '*/*'
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ApiResponse'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /api/v1/user/login:
    post:
      tags:
      - user-controller
      summary: login
      operationId: loginUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: loginData
        description: loginData
        required: true
        schema:
          $ref: '#/definitions/LoginRequestDto'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ApiResponse'
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /api/v1/user/logout:
    get:
      tags:
      - user-controller
      summary: logout
      operationId: logoutUsingGET
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Authorization
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ApiResponse'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /api/v1/user/signup:
    post:
      tags:
      - user-controller
      summary: signUp
      operationId: signUpUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: loginData
        description: loginData
        required: true
        schema:
          $ref: '#/definitions/UserInfoData'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ApiResponse'
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /error:
    get:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingGET
      produces:
      - text/html
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
    head:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingHEAD
      consumes:
      - application/json
      produces:
      - text/html
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        204:
          description: No Content
        401:
          description: Unauthorized
        403:
          description: Forbidden
    post:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingPOST
      consumes:
      - application/json
      produces:
      - text/html
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
    put:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingPUT
      consumes:
      - application/json
      produces:
      - text/html
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
    delete:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingDELETE
      produces:
      - text/html
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        204:
          description: No Content
        401:
          description: Unauthorized
        403:
          description: Forbidden
    options:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingOPTIONS
      consumes:
      - application/json
      produces:
      - text/html
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        204:
          description: No Content
        401:
          description: Unauthorized
        403:
          description: Forbidden
    patch:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingPATCH
      consumes:
      - application/json
      produces:
      - text/html
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        204:
          description: No Content
        401:
          description: Unauthorized
        403:
          description: Forbidden
definitions:
  ApiResponse:
    type: object
    properties:
      data:
        type: object
        properties: {}
      error:
        type: string
      message:
        type: string
      status:
        type: string
        enum:
        - "100"
        - "101"
        - "102"
        - "103"
        - "200"
        - "201"
        - "202"
        - "203"
        - "204"
        - "205"
        - "206"
        - "207"
        - "208"
        - "226"
        - "300"
        - "301"
        - "302"
        - "303"
        - "304"
        - "305"
        - "307"
        - "308"
        - "400"
        - "401"
        - "402"
        - "403"
        - "404"
        - "405"
        - "406"
        - "407"
        - "408"
        - "409"
        - "410"
        - "411"
        - "412"
        - "413"
        - "414"
        - "415"
        - "416"
        - "417"
        - "418"
        - "419"
        - "420"
        - "421"
        - "422"
        - "423"
        - "424"
        - "426"
        - "428"
        - "429"
        - "431"
        - "451"
        - "500"
        - "501"
        - "502"
        - "503"
        - "504"
        - "505"
        - "506"
        - "507"
        - "508"
        - "509"
        - "510"
        - "511"
      statusCode:
        type: integer
        format: int32
      timestamp:
        type: integer
        format: int64
    title: ApiResponse
  EvaSearchReqDto:
    type: object
    properties:
      ClientId:
        type: string
      EndUserIp:
        type: string
      Password:
        type: string
      UserName:
        type: string
    title: EvaSearchReqDto
  FlightInfo:
    type: object
    properties:
      Destination:
        type: string
      FlightCabinClass:
        type: string
      Origin:
        type: string
      PreferredArrivalTime:
        type: string
      PreferredDepartureTime:
        type: string
    title: FlightInfo
  FlightSearchInfo:
    type: object
    properties:
      AdultCount:
        type: string
      ChildCount:
        type: string
      DirectFlight:
        type: string
      EndUserIp:
        type: string
      InfantCount:
        type: string
      JourneyType:
        type: string
      OneStopFlight:
        type: string
      PreferredAirlines:
        type: string
      Segments:
        type: array
        items:
          $ref: '#/definitions/FlightInfo'
      TokenId:
        type: string
    title: FlightSearchInfo
  LoginRequestDto:
    type: object
    properties:
      accessToken:
        type: string
      newPassword:
        type: string
      password:
        type: string
      userName:
        type: string
    title: LoginRequestDto
  ModelAndView:
    type: object
    properties:
      empty:
        type: boolean
      model:
        type: object
        properties: {}
      modelMap:
        type: object
        additionalProperties:
          type: object
          properties: {}
      reference:
        type: boolean
      status:
        type: string
        enum:
        - "100"
        - "101"
        - "102"
        - "103"
        - "200"
        - "201"
        - "202"
        - "203"
        - "204"
        - "205"
        - "206"
        - "207"
        - "208"
        - "226"
        - "300"
        - "301"
        - "302"
        - "303"
        - "304"
        - "305"
        - "307"
        - "308"
        - "400"
        - "401"
        - "402"
        - "403"
        - "404"
        - "405"
        - "406"
        - "407"
        - "408"
        - "409"
        - "410"
        - "411"
        - "412"
        - "413"
        - "414"
        - "415"
        - "416"
        - "417"
        - "418"
        - "419"
        - "420"
        - "421"
        - "422"
        - "423"
        - "424"
        - "426"
        - "428"
        - "429"
        - "431"
        - "451"
        - "500"
        - "501"
        - "502"
        - "503"
        - "504"
        - "505"
        - "506"
        - "507"
        - "508"
        - "509"
        - "510"
        - "511"
      view:
        $ref: '#/definitions/View'
      viewName:
        type: string
    title: ModelAndView
  UserInfoData:
    type: object
    properties:
      emailAddr:
        type: string
      location:
        type: string
      userName:
        type: string
    title: UserInfoData
  View:
    type: object
    properties:
      contentType:
        type: string
    title: View
